### ISSUE TITLE
bug: intermitent test failures in apple adapter, when not touching that codepath

### ISSUE THREAD

**Issue by jzacsh** [dtinit/data-transfer-project#1411]
the failures always look like:

```
AppleMusicImporterTest > testImportPlaylistTracksFailure() PASSED

AppleMusicImporterTest > testImportPlaylistTracks() FAILED
    Wanted but not invoked:
    appleMusicInterface.importMusicPlaylistItemsBatch(
        "554bce6f-0b2d-4f08-85f0-1225da0b1e81",
        []
    );
    -> at org.datatransferproject.datatransfer.apple.music.AppleMusicInterface.importMusicPlaylistItemsBatch(AppleMusicInterface.java:228)
    Actually, there were zero interactions with this mock.
        at org.datatransferproject.datatransfer.apple.music.AppleMusicInterface.importMusicPlaylistItemsBatch(AppleMusicInterface.java:228)
        at org.datatransferproject.datatransfer.apple.music.AppleMusicImporterTest.testImportPlaylistTracks(AppleMusicImporterTest.java:197)

AppleMusicImporterTest > importTwoPlaylistItemsInDifferentPlaylists() PASSED
```

recent instances of this showing up:
- https://github.com/dtinit/data-transfer-project/actions/runs/12245562679/job/34159697023?pr=1410
- https://github.com/dtinit/data-transfer-project/actions/runs/12238886816/job/34138018880
- https://github.com/dtinit/data-transfer-project/pull/1405/checks?check_run_id=34001881475
- https://github.com/dtinit/data-transfer-project/actions/runs/12188580079/job/34001881475?pr=1404

**Comment by jzacsh** [comment]
only working on this for a moment because it's blocking me again. (if it fades, and I get my PR in then I'll need to drop this hot-potato for the moment)

**Comment by jzacsh** [comment]
ah figured it out: [createTestPlaylistItems](https://github.com/dtinit/data-transfer-project/blob/e820d25d15c3136c7f18fa1d62806a16ec74b707/extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/music/AppleMusicImporterTest.java#L293) is sometimes returning an empty list.
